- ckanext/spatial/public/js/dataset_map.js
bbox map display issue as described in https://github.com/ckan/ckanext-spatial/issues/90
> [#90] bbox display issue when cross international date line

- ckanext/spatial/templates/spatial/snippets/map_attribution.html
> Display map widget custom attribution

- doc/spatial-search.rst
> Tip about using reindex.

- ckanext/spatial/plugin.py
Because plugins are loaded for every paster command, regardless of which
paster command is being run, when lots of plugins are installed paster startup
time can be substantial.
To fix this, making sure that plugin.py in various extensions doesn't
import unnecessary (and potentially slow) modules, this PR moves the
imports of some function into the function where they are called - but 
only for plugin.py
This reduces paster startup time (for me) by up to .5 seconds, which
while not significant by itself, contributes to my current 8 second
startup time.
> Speed up non-spatial paster commands.

- ckanext/spatial/lib/csw_client.py
> fix CSW constructor

- doc/csw.rst
> adjust pycsw requirements docs

- ckanext/spatial/plugin.py
Improving log error message for invalid geoJSON data.
> Improving log error message.

- ckanext/spatial/controllers/view.py
This function was removed in ckan/ckan@34f3f18
> Remove import of base.redirect

- ckanext/spatial/controllers/api.py
- ckanext/spatial/helpers.py
- ckanext/spatial/plugin.py
- ckanext/spatial/validation/validation.py
Fix for https://github.com/ckan/ckanext-spatial/issues/174
> Fix IOError when opening metadata schema #174

- .travis.yml
- README.rst
> Fix travis build

- doc/install.rst
This follows query: https://stackoverflow.com/q/47087357/1512326
> Install instructions more explicit

- ckanext/spatial/plugin/__init__.py
_params_for_solr_search should extend fq_list not replace it.
> Make _params_for_solr_search extend fq_list

- ckanext/spatial/harvesters/base.py
> Make ckanext.spatial.harvest.validate_wms working again #265

- ckanext/spatial/harvesters/base.py
> Lineage support

- .github/workflows/test.yml
- ckanext/spatial/plugin/__init__.py
- ckanext/spatial/templates/spatial/snippets/dataset_map_base.html
Refs https://github.com/ckan/ckan/issues/6787
> CKAN 2.10 support

- ckanext/spatial/plugin/__init__.py
- ckanext/spatial/tests/test_spatial_search.py
Allow `GeometryCollection` for one-to-many Dataset-Geographies relations.
> Allow Multiple Geometries

- ckanext/spatial/harvesters/waf.py
Add more parser to handle IIS server. This will fix https://github.com/ckan/ckanext-spatial/issues/319.
> add more date parser for IIS server

- .github/workflows/test.yml
- ckanext/spatial/util.py
- requirements.txt
Fixes #340 
Bumps Shapely and handles owslib across python versions
> Fix requirements versions

- ckanext/spatial/harvesters/waf.py
For https://github.com/ckan/ckanext-spatial/issues/336
The current scraper only handles files
```
Tuesday, June 30, 2015  2:41 PM        15649 a.xml
```
This new scraper handles both files and dirs
```
Tuesday, June 30, 2015  3:41 PM        <dir> mydir
Tuesday, June 30, 2015  3:30 PM        13867 one.xml
```
> traverse IIS folders

- requirements.txt
There are issues with the Shapely 
https://github.com/shapely/shapely/issues/2198
> bump Shapely
