ckan/ckanext-spatial

- ckanext/spatial/nongeos_plugin.py
- setup.py
Just a naive implementation to make wms and geojson preview compatible for the new "IResourceView" interface, which introduced in CKAN 2.3. They are "wms_view" and "geojson_view".
The old "wms_preview" and "geojson_preview" are still available for CKAN version 2.2 or lower.
> Resource preview for IResourceView in CKAN 2.3 (2nd try)

- ckanext/spatial/harvesters/csw.py
Records deleted on the remote CSW server are not deleted locally.
The ids of the records stored locally but no longer on the remote server are put in the fetch list, but the fetch stage will fail because the record is not found on the CSW server. The transaction object will be marked as failed, and the record as not current.
The fix just bypasses the fetch stage if the record has to be deleted.
> Fix delete in CSW. Closes #103.

- ckanext/spatial/public/js/dataset_map.js
This limits previous fix to apply only when coordinates start with positive longitude and ends with negative longitude, which is the obvious scenario we want to fix. It wont affect coordinates that start from east(max-longitude) to west(min-longitude), or right to left, when both longitude are positives or negatives.
> [#112] bbox fix only kicks in with positive w-long and negative e-long

- ckanext/spatial/model/harvested_metadata.py
Support multiple GML namespace URIs to cover various ISO metadata dialects (per https://github.com/GeoNode/geonode/issues/2187#issuecomment-112996898)
> support multiple GML namespaces

- doc/install.rst
- pip-requirements.txt
Tested with 2.7. Its only the WAF harvester that currently uses it, and that is only basic use.
> [#2470] Allow newer requests versions. 

- doc/spatial-search.rst
In the section "Dataset Extent Map" the advice on  {% ckan_extends %} is given, but not in the earlier one for the search widget. Wasted 2min of my life, hence fixing! :P
> Mention {% ckan_extends %} in spatial search widget docs

- ckanext/spatial/templates/spatial/snippets/map_attribution.html
If ckanext.spatial.common_map.type = custom then the map data is not necessarily &copy; OpenStreetMap (e.g. I am using swisstopo's maps and WMTS). But this was rendered nonetheless. Now, in that case, only the attribution set by ckanext.spatial.common_map.attribution is shown. Otherwise behaviour doesn't change. Hope that makes sense.
> fix map attribution

- ckanext/spatial/public/js/common_map.js
Set the L.TileLayer as a TMS. It's required if the base layer specified in custom.url is a TMS. The default value of tms is false in Leaflet.
To use the TMS option, ```ckanext.spatial.common_map.tms = true``` has to be set in the ckan .INI file.
Same as https://github.com/ckan/ckanext-geoview/pull/24
> Set tms option for custom layer

- ckanext/spatial/lib/csw_client.py
cc @FuhuXia
As per https://github.com/geopython/pycsw/issues/301, this PR forces CKAN's CSW client to explicitly set sorting so that a given CSW server can return results in a consistent manner.
> force all CSW GetRecords requests to set ogc:SortBy to ensure proper ordering

- ckanext/spatial/harvesters/base.py
Dear All,
the purpose of this pull request is to provide the possibility to assign the license id
to a package from the gmd:useLimitation metadata element.
In some cases I needed to do that in the CSW harvesting because the current code set 
only the extras fields but not the package 'license_id' (this means no license link available 
from the left side menu and avoid the possibility to search dataset by license).
As I know a metadata could contain multiple occurrences of the gmd:uselLimitation element,
so my code assigns to the package the first license that match in the available licenses list of Ckan.
> Metadata license ID check for package

- ckanext/spatial/plugin.py
- doc/spatial-search.rst
Updates solr-spatial-field query method for Solr 5 compatibility. Tested on Solr 5.3.0. Based on https://gist.github.com/u10313335/5649488bc3a4037e1357 which resolves #114 according to comments in that issue.
> #114 solr-spatial-field search Solr 5 compatibility

- ckanext/spatial/plugin.py
[Most] versions of shapely do not have `geometry` imported at the top level. Import it explicitly to prevent indexing errors instead of relying on import side-effects.
> Fix missing import in before_index

- setup.py
When trying to pip install a checkout of ckanext-spatial, any further attempt to interact with the virtualenv (python or pip) breaks with a KeyError: 'ckanext'.  
This appears to be documented at:  https://github.com/ckan/ckanext-pdfview/issues/17 and https://github.com/ckan/ckanext-geoview/issues/39
> Remove ckanext.spatial from namespace_packages in setup

- .travis.yml
- bin/travis-build.bash
- ckanext/spatial/tests/test_harvest.py
Tests were relying on _rest action calls which have now been removed in
master (and 2.8) and therefore tests were failing.
Makes the tests work, although there is probably some effort required in
determining why metadata_modified is not being returned from
package_show calls.
Also caches the pip output and only tests again latest version of CKAN.  For some reason, apart from the first test the following tests were attempting to run with postgres 10.1
> Fix broken tests

- pip-requirements.txt
This patch fixes an issue where new versions of GeoAlchemy2 caused crashes.
We've locked the dependency to a known, working version.
> fix crash caused by new GeoAlchemy2 version

- ckanext/spatial/tests/test_harvest.py
There may be cases where the key is not present (this is particularly true of `verified` which is unset by default).  This is currently raising a KeyError, rather than an AssertionError.
> The expected key may not be set - this stops a KeyError

- ckanext/spatial/model/harvested_metadata.py
Should support gmx:MimeFileType instead of gco:CharacterString in the resources' gmd:Name tag
```
<gmd:name>
<gmx:MimeFileType type="application/octet-stream">
Fichier KMZ à télécharger
</gmx:MimeFileType>
</gmd:name>
```
> [harvest] fixes https://github.com/ckan/ckanext-spatial/issues/225

- ckanext/spatial/model/harvested_metadata.py
I saw the language specified as this.  
```
<gmd:language>
<gco:CharacterString>en</gco:CharacterString>
</gmd:language>
```
Example [here](https://gitlab.com/datopian/ckan-ng-harvest/blob/develop/harvest/csw/samples/sample2.xml#L5-7).
I'm not sure if this is ok with ISO but this CSW source is using it.
> New path for languages

- bin/ckan_pycsw.py
Fixes #232: ckan-pycsw is not compatible with recent pycsw versions
> #232: Fix pycsw imports

- ckanext/spatial/lib/__init__.py
- ckanext/spatial/plugin/__init__.py
- ckanext/spatial/tests/lib/test_spatial.py
- ckanext/spatial/tests/model/test_package_extent.py
> Update shapely usage to avoid deprecation

- ckanext/spatial/harvesters/waf.py
To allow WAF subdirectories to be harvested, the contents must be converted to string under python 3.
> Apply byte->str conversion to recursive call

- ckanext/spatial/harvesters/waf.py
This addition will allow the `last-modified` date for XML records to be stored in the harvest database, if the WAF server is based on nginx instead of apache.   When no `last-modified` dates are stored in the database, every XML record is always reharvested, even if it was never changed.  This can get very expensive if the WAF has thousands of records.
The HTML formatting for apache and nginx directory listings are, as far as I understand, identical with each other.   But in case the formatting should ever change, it might make sense to have a separate (and currently identical) parser for nginx.
> Add nginx WAF server

- .github/workflows/test.yml
- requirements-py2.txt
- requirements.txt
Shapely 2.0.0 removed deprecated asShape, which causes errors if it installed. Python 3.6 was removed from github actions, so this upgrades that as well
> Pin shapely

- ckanext/spatial/tests/test_api.py
- ckanext/spatial/util.py
These changes seem necessary to resolve the link `/harvest/object/<id>/html` under CKAN 2.9 and python 3.
> Fix HTML view of ISO XML

- .github/workflows/test-postgis.yml
- .github/workflows/test.yml
- README.rst
- doc/install.rst
- requirements-py2.txt
- requirements.txt
Related to #301 
`pyproj==2.6.1` is not workign for Python >= 3.9
This PR starts defining proper test for each possible environment
The requirements.txt file update packages for python >= 3.9:
- from `Shapely>=1.2.13,<2.0.0` to `Shapely==2.0.1`
- from `pyproj==2.6.1` to `pyproj==3.4.1`
- from `OWSLib==0.18.0` to `OWSLib==0.28.1`
- from `geojson==2.5.0` to `geojson==3.0.1`
**Incredibly, it look like all test are green for all those new packages**
Geometries commands for the RIDL application are working fine. 
Alpine has a fixed Python version. It can not be easily changed.
You can't use Python 3.8 or 3.9 with Alpine 3.16.
We use Alpine 3.16 for CKAN 2.10 image
If we want to test this extension with CKAN 2.10 and Python 3.8 we will need a new approach.
**Should we start building CKAN 2.10 …
> Upgrade tests to check all envs, including CKAN 2.10 with Python 3.10

- ckanext/spatial/search/__init__.py
Problem:
There is an assumption in the code [that geometry may be missing from the metadata](https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/search/__init__.py#L52-L53)
But code [doesn't handle TypeError](https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/search/__init__.py#L25) which is raised in this case. 
Solution:
Skip an attempt to parse missing geometry as a JSON value + explicitly notify user about missing geometry.
> TypeError when spatial is missing

- ckanext/spatial/harvesters/waf.py
Need this fix to scape file date from **Microsoft-IIS/10.0** server.
Base on the [IIS release history](https://learn.microsoft.com/en-us/lifecycle/products/internet-information-services-iis), 
`IIS 7.5` is on Windows 7/Windows Server 2008 R2* back to 2009. It has been `IIS 10` starting 2015.
> detecting Microsoft-IIS server

- ckanext/spatial/harvesters/base.py
`six.text_type` returns `str` for python3, using `str` as validator generates the following error seen on `v2.0.0`.
```
...
File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/queue.py", line 515, in fetch_and_import_stages
success_import = harvester.import_stage(obj)
File "/home/vcap/deps/1/src/ckanext-spatial/ckanext/spatial/harvesters/base.py", line 721, in import_stage
package_id = p.toolkit.get_action('package_update')(context, package_dict)
File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/logic/__init__.py", line 551, in wrapped
result = _action(context, data_dict, **kw)
...
File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/logic/__init__.py", line 551, in wrapped
result = _action(context, data_dict, **kw)
File …
```
> change str validator to unicode_safe

- ckanext/spatial/lib/csw_client.py
Fixes #310 
New owslib version has a constructor which allows building csw client for version 2.0.2 and version 3.0.0. As the csw_client is directly inherited from the old owslib csw client, this just maintains the old functionality without supporting version 3.0.0.
> Use csw2 from owslib

- requirements.txt
Using latest from github was a workaround which now has failed if running on python 3.9, but since 3.6.1 was released, the workaround is no longer required.
> latest pyproj requires python 3.10, lock the version to released 3.6.1

- ckanext/spatial/search/__init__.py
When datasets have the wrong geospatial coverage value, they aren’t indexed so users won’t know of them and can’t update/ delete them:
```
ckan search-index rebuild -ei
2024-03-13 02:12:13,066 INFO  [ckan.cli] Using configuration file /etc/ckan/default/production.ini
2024-03-13 02:12:13,067 INFO  [ckan.config.environment] Loading static files from public-bs3
2024-03-13 02:12:13,267 WARNI [ckan.common] Option ckan.plugins is not declared
2024-03-13 02:12:13,494 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates-bs3
2024-03-13 02:12:13,714 WARNI [ckan.common] Option ckanext.xloader.max_content_length is not declared
2024-03-13 02:12:13,714 WARNI [ckan.common] Option ckanext.xloader.max_type_guessing_length is not declared
2024-03-13 …
```
> Fix catch error on index

- ckanext/spatial/public/js/spatial_query.js
In our particular customisation of CKAN we have 2 forms with the class of 'search-form', and this class is used to ensure styling consistency.
With the way this was set up before, both forms were getting a ext_bbox input injected into them, but then only the first one on the page was getting the bbox value set on it. This unfortunately was not the search form that actually needed the bbox value.
With these changes, I'm trying to scope the ext_bbox input to only the actual dataset search form.
In general, I think actions like this should try to target elements by ID's where possible, rather than using classes, which should be used more for defining styling to be applied to that class, but unsure what the CKAN team preferences are on this.
> Ensure the bbox input is in the correct form

- CHANGELOG.md
- ckanext/spatial/public/js/common_map.js
When a map provider is not configured, this doc link leads to un-styled error page.
Current error link vs correct link:
`https://docs.ckan.org/projects/ckanext-spatial/en/latest/map-widgets.html`
`https://docs.ckan.org/projects/ckanext-spatial/en/latest/map-widgets/`
> update map-widgets documentation link
